# Generated by Django 3.2.21 on 2023-09-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='Название камеры',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='Rtsp ссылка',
            new_name='rtsp_url',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='Дата и время события',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='Описание',
            new_name='descrpiption',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='Название сериса',
            new_name='name_service',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Имя пользователя',
            new_name='name',
        ),
    ]
