# Generated by Django 3.2.21 on 2023-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0004_auto_20231001_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='level_event',
            field=models.CharField(max_length=50),
        ),
    ]
