# Generated by Django 3.2.21 on 2023-10-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0006_alter_logs_level_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='level_event',
            field=models.TextField(max_length=100),
        ),
    ]
