# Generated by Django 3.2.21 on 2023-10-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0007_alter_logs_level_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtsp_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rtsp_server', models.CharField(max_length=100)),
                ('input_rtsp', models.TextField()),
                ('output_rtsp', models.TextField()),
            ],
            options={
                'verbose_name': 'Rtsp сервер',
                'verbose_name_plural': 'Rtsp сервер',
            },
        ),
    ]
