# Generated by Django 3.2.21 on 2023-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0008_rtsp_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('ftp_login', models.TextField()),
                ('ftp_password', models.TextField()),
            ],
            options={
                'verbose_name': 'Фтп',
                'verbose_name_plural': 'Фтп',
            },
        ),
    ]
